sudo: required
services:
  - docker

before_install:
  - docker build -t nazzer15/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nazzer15/react-test npm test

after_success:
  - docker build -t nazzer15/multi-client ./client
  - docker build -t nazzer15/multi-nginx ./nginx
  - docker build -t nazzer15/multi-server ./server
  - docker build -t nazzer15/multi-worker ./worker

  # Log in to the docker CLI

  # Take